name = "okg-api"
main = "src/index.js"
compatibility_date = "2024-12-01"

[vars]
ORIGIN = "https://openknowledgegraphs.com"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE"
index_name = "okg-catalog"

[[d1_databases]]
binding = "DB"
database_name = "okg-logs"
database_id = "bd880501-9e56-4102-a810-975631aeb045"
